name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          extensions: mbstring, xml, json, bcmath, sqlite3, pdo_sqlite

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run tests with coverage
        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text --coverage-clover=clover.xml

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/${{ github.ref_name }}-coverage.svg
          push_badge: false

      - name: Git push to badges branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: badges
          keep_files: true
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
